workmates/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  root "people#index"

  resources :people

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

workmates/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

workmates/app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: true
  has_attached_file :image, styles: {large: "600x600>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type:  /\Aimage\/.*\Z/

end

workmates/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

workmates/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_filter :require_login

  private

    def require_login
      unless current_user
        redirect_to login_url
      end
    end
end

workmates/app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def new
     @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      flash[:notice] = "Person has been created."
      redirect_to @person
    else
      flash[:notice] = "Person has not been created."
      render "new"
    end
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
     @person = Person.find(params[:id])
     if @person.update(person_params)
       flash[:notice] = "Person has been updated."
       redirect_to @person
     else
       flash[:alert] = "Person has not been updated."
       render "edit"
     end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    flash[:notice] = "Person has been deleted."
    redirect_to people_path
  end

  private

  def person_params
     params.require(:person).permit(:name, :lastname, :title, :image)
  end
end

workmates/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to people_url
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

workmates/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

workmates/app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
      case level
        when 'notice' then "alert alert-info"
        when 'success' then "alert alert-success"
        when 'error' then "alert alert-error"
        when 'danger' then "alert alert-danger"
      end
  end
end

workmates/app/helpers/persons_helper.rb
module PersonsHelper
  def fullname ( person )
    "#{person.name} #{person.lastname}"
  end
end

workmates/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # define logged_in
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

workmates/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workmates</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>">
                <%= value %>
          </div>
    <% end %>
    <%= yield %>
  </body>
</html>

workmates/app/views/people/_form.html.erb
<%= form_for(@person, html: {multipart: true}) do |f| %>
  <% if @person.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@person.errors.count, "error") %>
     prohibited this project from being saved:</h2>
     <ul>
       <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
       <% end %>
  </ul> </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
</p>
<p>
  <%= f.label :lastname %><br>
  <%= f.text_field :lastname %>
</p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>
<p>
  <%= f.label :image %>
  <%= f.file_field :image %>
</p>

  <%= f.submit %>
<% end %>

workmates/app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= render "form", person: @person %>

workmates/app/views/people/index.html.erb
<% if logged_in? %>
  <%= link_to "Log out", logout_path, method: :delete %>
<% end %>
<div class="people">
  <h1>People</h1>
    <%= link_to "New Person", new_person_path, class: "print" %>
    <div id="people">
        <% @people.each do |person| %>
        <div class="person">
          <%= image_tag person.image.url(:large), class: "portrait" %>
          <div class="plate">
            <%= link_to fullname(person), person, class: "name"%>
            <i class="fa fa-pencil"></i>
            <p class="title"><%= person.title %></p>
          </div>
        </div>
      <% end %>
  </div>
</div>

workmates/app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@person.errors.count, "error") %>
     prohibited this project from being saved:</h2>
     <ul>
       <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
       <% end %>
  </ul> </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
</p>
<p>
  <%= f.label :lastname %><br>
  <%= f.text_field :lastname %>
</p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>
<p>
  <%= f.label "Load image" %>
  <%= f.file_field :image %>
</p>

  <%= f.submit %>
<% end %>

workmates/app/views/people/show.html.erb
<%= image_tag @person.image.url(:large) %>
<p><%=@person.name%> <%=@person.lastname %></p>
<p><%= @person.title %></p>



<%= link_to "Edit Person", edit_person_path(@person) %>
<%= link_to "Delete Person",
            person_path(@person),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this person?" }
%>